name: Optimize images
on:
  pull_request:
    branches:    
      - 'main'
jobs:
  build:
  if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.REPO_SCOPED_TOKEN }}
